### ISSUE TITLE
ScaleTransition

### ISSUE THREAD

**Issue by hiashutoshsingh** [hiashutoshsingh/flutter-animation_examples#7]
Refer this [link](https://api.flutter.dev/flutter/widgets/ScaleTransition-class.html)

**Comment by iamsureshsharma** [comment]
@hiashutoshsingh I want to add this animation example also

**Comment by hiashutoshsingh** [comment]
@iamsureshsharma  Thanks for making all the effort. I really appreciate that. 🤟🏽
